export const GET_GITHUB_USER = 'GET_GITHUB_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
